from sqlalchemy.exc import OperationalError, ProgrammingError, SQLAlchemyError
from sqlalchemy import text
from datetime import datetime
from typing import Optional

from app.entities.charts import Chart
from app.entities.chart_data import ChartData

def generate_assistant_content_and_chart_data(
    query: Optional[str],
    session,
    history,
    message
) -> str:
    """
    Execute an SQLite query generated by LLm model and proccess the result.
    
    Args:
        querry (str): Sqlite query generated by natural language.
        session: SQLAlchemy instance.
        history: QueryHistory associed to this message.
        message: Message instance of "user" type.
        
    Returns:
        str: Textual content of "assistant" message.
    """
    try:
        
        if not query:
            return """
Im not sure how to turn that into a valid chart

Try asking something like:
    - "Which products sold the most on Sunday?"
    - "Total revenue by weekday"
    - "Compare sales between waiters"
            """
        
        result = session.execute(text(query))
        rows = result.fetchall()

        print(f"Query result rows count: {len(rows)}")
        print(f"Rows: {rows}")

        valid_rows = [row for row in rows if row and len(row) == 2 and row[0] is not None and row[1] is not None]

        if not valid_rows:
            try:
                last_date_result = session.execute(text("SELECT MAX(DATE(date)) FROM sales")).scalar()
                if last_date_result:
                    formated_date = datetime.strptime(last_date_result, "%Y-%m-%d").strftime("%B %d, %Y")
                    return (
                        f"No results were found for your query. "
                        f"The latest date registered in your database is {formated_date}. "
                        "Try rephrasing your question or adjusting the time period."
                    )
                else:
                    return "No results were found and the sales table appears to be empty."
            except Exception as error:
                return (
                    f"No results were found for your query. "
                    f"(Additionally, an error occurred while checking the latest date: {str(error)})"
                )

        # Si hay datos válidos, generar el chart
        chart = Chart(
            history_id=history.id,
            chart_type="bar",
            title=message.content[:30],
            x_axis="label",
            y_axis="value",
        )
        session.add(chart)
        session.commit()
        session.refresh(chart)

        for label, value in valid_rows:
            chart_data = ChartData(
                chart_id=chart.id,
                label=str(label),
                value=float(value)
            )
            session.add(chart_data)

        session.commit()
        return "This is your generated chart: **{chart.title}** of your query"

    except OperationalError as oe:
        return f"There was a problem executing your query. It might be a syntax error or invalid column.\nDetails: {str(oe.orig)}"

    except ProgrammingError as pe:
        return f"The query could not be executed due to a database error. Please check your input.\nDetails: {str(pe.orig)}"

    except SQLAlchemyError as se:
        return f"An unexpected error occurred while accessing the database.\nDetails: {str(se)}"

    except Exception as e:
        return f"Unexpected error: {str(e)}"
